config/routes.rb
Rails.application.routes.draw do

  get 'show_user' => 'epicenter#show_user'

  get 'epicenter/now_following'

  get 'feed' => 'epicenter#feed'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  resources :tweets
  devise_for :users
  
  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags

	before_validation :link_check

	validates :message, presence: true, length: { maximum: 140, too_long: "A tweet can only be 140 characters long."}

	private

	def link_check
		if self.message.include?("http://")
			array = self.message.split

			index = array.map { |word| word.include? "http://"}.index(true)

			self.link = array[index]

			if array[index].length > 23
				array[index] = "#{array[index][0..20]}..."
			end	

			self.message = array.join(" ")
		end	
	end

	def apply_link
		array = self.message.split

		index = array.map { |word| word.include? "http://"}.index(true)
		url = array[index] unless index.nil?


		unless index.nil?
			array[index] = "<a href='#{self.link}' target='_blank'#{url}</a>"
		end	
		
		self.message = array.join(" ")
	end	
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  serialize :following, Array

  validates :username, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])

  	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end	
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  before_action :authenticate_user!

  def tag_tweets
    @tag = Tag.find(params[:id])
  end  

  def feed
  	@following_tweets = []

  	Tweet.all.order(created_at: :desc).each do |tweet|
  		if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id

  			@following_tweets.push(tweet)

  		end	
  	end
  end

  def all_users
    @users = User.all
  end  

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	current_user.following.push(id: params[:id])
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  	# redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	current_user.following.delete('id' => params[:id])
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?('id' => user.id.to_s)
        @users.push(user)
      end  
    end  
  end  

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?('id' => @user.id.to_s)
        @users.push(user)
      end  
    end
  end  

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)
      
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def get_tagged(tweet)
		message_array = tweet.message.split 

	    message_array.each_with_index do |word, index|
	      if word[0] == "#"
	        # see if tag exits (save it as a var for the tweet creation)
	        if Tag.pluck(:phrase).include?(word)
	          tag = Tag.find_by(phrase: word)
	        else  
	        # make a new tag
	          tag = Tag.create(phrase: word)
	        end
	        tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)

	        message_array[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
	      end  
	    end

	    tweet.update(message: message_array.join(" "))
	    tweet
	end
end

app/views/epicenter/_users_list.html.erb
<div class="container_fluid">
	<div class="row">
		<% @users.each do |user| %>
			<div class="col-md-3">
				<div class="well user-list-wells">
					<div class="row">
						<div class="col-md-6">
							<%= image_tag user.avatar.url, class: 'img-responsive' %>
						</div>

						<div class="col-md-6">
							<% if current_user.following.include?( "id" => user.id.to_s) %>
								<%= link_to "Following", unfollow_path(id: user.id), class: 'btn btn-primary', id: 'unfollow_btn' %>
							<% else %>
								<% if current_user.id != user.id %>
									<% link_to "Follow", now_following_path(id: user.id), class: 'btn btn-primary' %>
								<% end %>
							<% end  %>
						</div>

						</div>
						<div class="row">
							<%= link_to show_user_path(id: user.id) do %>
								<h3><%= user.name %></h3>
								<p>@<%= user.username %></p>
							<% end %>
							<p>
								<%= user.bio %>
							</p>	
						</div>

					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/epicenter/all_users.html.erb
<%= render 'users_list' %>

app/views/epicenter/feed.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3
                col-sm-8 col-sm-offset-2
                col-xs-10 col-xs-offset-1">
      <h1><%= current_user.username %>'s Squaker Feed</h1>
      <p>Here is what you "friends" are saying:</p>
      <div>
        <% @following_tweets.each do |tweet| %>
          <div class="well">
          	<p>
          		<%= image_tag tweet.user.avatar.url, class: 'user-pic-nav img-responsive' %>
          		<%= link_to tweet.user.name, show_user_path(id: tweet.user_id) %>
          		<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %>
          		<%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
          		<%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %> 
          	</p>	

          	<p>
          		<%= tweet.message.html_safe %>
          	</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/epicenter/followers.html.erb
<h2><%= @user.name %>'s followers</h2>

<%= render 'users_list' %>

app/views/epicenter/following.html.erb
<h2><%= @user.name %> is following</h2>

<%= render 'users_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1><%= @user.username %>'s Profile & Tweets</h1>
<h1><%= current_user.following %></h1>

<p><%= @user.name %></p>
<p><%= @user.location %></p>
<p><%= @user.bio %></p>

<p>
    <% if current_user.following.include?( "id" => @user.id.to_s) %>
        <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: 'unfollow_btn' %>
    <% else %>
        <% if current_user.id != @user.id %>
            <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
        <% end %>
    <% end %>
</p>

<% @user.tweets.each do |tweet| %>
    <div>
        <p>@<%= @user.username %></p>
    <p><%= tweet.message %></p>
    </div>
<% end %>

app/views/epicenter/tag_tweets.html.erb
<div class="container-fluid">
	<div class="text-center">
		<h1><%= @tag.phrase %></h1>
	</div>
	
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<% @tag.tweets.each do |tweet| %>
			<p>
				<%= tweet.user.name %> <%= "#{tweet.user.username}" %> - <%= time_ago_in_words(tweet.created_at) %>
			</p>

			<p>
				<%= tweet.message.html_safe %>
			</p>

			<p>
				<%= link_to 'Back', tweets_path  %>
			</p>
			<% end  %>
		</div>
	</div>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Squaker", feed_path, class: "navbar-brand" %>
      <!-- <a class="navbar-brand" href="#">Squaker</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Tweets", tweets_path, class: "btn" %></li>
        <li><%= link_to "All Users", all_users_path, class: "btn" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New Tweet', new_tweet_path, {class: 'btn btn-success', style: 'margin-right: 1em'} %></li>
        <%if current_user  %>
          <% if current_user.avatar.url  %>
            <li><%= image_tag current_user.avatar.url, {style: 'height: 30px; margin-top: .5em;', class: 'img-responsive'}%></li>
          <% end %>
          <li><%= link_to "Edit User", edit_user_registration_path, class: "btn" %></li>    
        <% end %>
        
        <li><%= link_to "Log Out", destroy_user_session_path, class: "btn", method: :delete, data: { confirm: 'Are you sure?' }%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="container-fluid">   
  <div class="row">
    <div class="col-md-2">

      <%= form_with(model: tweet, local: true) do |form| %>
        <% if tweet.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

            <ul>
            <% tweet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :message %>
          <%= form.text_field :message, id: :tweet_message %>
        </div>

        <div class="field">
          <%= form.hidden_field :user_id, value: current_user.id %>
        </div>

        <div class="actions">
          <%= form.submit "Send" %>
        </div>
      <% end %>
    </div>    
  </div>  
</div>  

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <h1>Tweets</h1>

    <table class="container table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Message</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.id%></td>
            <td><%= tweet.message.html_safe %></td>
            <td><%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %></td>
            <td><%= link_to 'Show', tweet %></td>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Tweet', new_tweet_path %>
  </div>  
</div>
<br>
    

app/views/tweets/new.html.erb
<div class="container-fluid">   
  <div class="row">
    <div class="col-md-2 col-md-offset-5">

			<h1>New Tweet</h1>

			<%= render 'form', tweet: @tweet %>

			<%= link_to 'Back', tweets_path %>
		</div>	
	</div>	
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user_id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>